-- ============================================================
-- Migration 026 — Waiter "Order More" (Dine-In + Pickup) support
-- Foodie Lover POS
--
-- Run in Supabase SQL editor:
--   https://supabase.com/dashboard/project/<project>/sql/new
--
-- SAFE TO RE-RUN: every statement uses IF NOT EXISTS / CREATE OR REPLACE.
--
-- ── Why this migration is small ───────────────────────────────────────────
-- Most of "Order More" needs NO schema change at all:
--   • Dine-In Order More already works at the data-model level via the
--     existing tab_id-grouping in POST /api/orders (a second confirmed
--     round on the same tab already gets its own `orders` row with the
--     same tab_id — see app/api/orders/route.ts). Only new server-side
--     GUARDS were needed there (tab-status revalidation, staff-session
--     check), which are plain application code, not schema.
--   • Pickup Order More needs a way to add MORE order_items to an
--     ALREADY-confirmed pickup order without disturbing the items already
--     sent to the kitchen. `order_items.item_status` already tracks each
--     item's own kitchen progress independently, so newly-added items
--     naturally show as "pending" alongside already-"ready"/"served" items
--     on the SAME order — no new "round" or "session" column is needed for
--     that. Which items are new for the PRINTER ticket is known directly
--     from the just-inserted item ids at write time, so no persistent
--     marker column is needed there either.
--   • Keeping Pickup Order More on the SAME order_id (rather than a new
--     linked "child order") means Finance (lib/finance-server.ts sums
--     completed pickup/delivery orders by individual order_id), Spin & Win
--     (spin_results.order_id UNIQUE), and receipts (email_queue/email_log
--     UNIQUE(order_id, ...)) all keep working completely unmodified — the
--     order's subtotal/total simply grow, and whichever of those systems
--     look at the order later see the correct combined amount exactly once.
--
-- What IS added, and why:
--   1. order_events.idempotency_key — order_events currently has no
--      idempotency support at all (unlike `orders`, which already has one —
--      migration_021). Pickup Order More is a NEW class of write (append
--      items to an order that already exists) that has the same "double
--      click / network retry must not duplicate" requirement the task
--      spec calls out explicitly (§A18) as order creation already has, so
--      it needs the same kind of guarantee. Reusing order_events (rather
--      than adding a new table) satisfies both jobs at once: it is already
--      the audit-trail table the task spec asks us to reuse (§A17), and a
--      partial unique index on (order_id, idempotency_key) gives an atomic,
--      race-proof duplicate check under concurrent submissions (§A19) —
--      which a check-then-insert from application code cannot guarantee.
--   2. add_pickup_order_items() — one SECURITY DEFINER function that does
--      the whole "validate eligibility → insert new items → recompute
--      order totals → write the audit/idempotency event" sequence as a
--      single locked transaction (FOR UPDATE on the orders row), modeled
--      on the existing create_vendor_payment() / create_salary_payment()
--      pattern (migration_023_finance_atomicity.sql). This is what makes
--      concurrent Order More submissions for the same pickup order safe
--      (two waiters, or a double-tap) instead of a multi-step sequence of
--      separate Supabase calls that could interleave.
-- ============================================================

-- ── 1. Idempotency support on order_events ──────────────────────────────────

ALTER TABLE order_events ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_events_order_idempotency
  ON order_events (order_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ── 2. add_pickup_order_items ────────────────────────────────────────────────
-- Atomically appends newly-ordered items to an already-confirmed Pickup
-- order ("Order More"). Item ids and the audit-event id are generated by
-- the caller (TypeScript), matching this codebase's existing convention
-- (create_vendor_payment/create_salary_payment/create_employee_salary_payment
-- all take their row ids as parameters rather than generating them in SQL).
--
-- p_items is a JSONB array of {id, menuItemId, name, qty, price, subtotal}.
--
-- Returns JSONB:
--   {ok:true,  alreadyExists:true,  orderId, newItemIds:[]}                     — idempotent replay
--   {ok:true,  alreadyExists:false, orderId, newItemIds:[...], newSubtotal, newTotal}
--   {ok:false, error:'order_not_found'}
--   {ok:false, error:'invalid_type', type}          — not a pickup order
--   {ok:false, error:'not_eligible', status}         — not pending/preparing/prepared
CREATE OR REPLACE FUNCTION public.add_pickup_order_items(
  p_event_id         TEXT,
  p_order_id         TEXT,
  p_restaurant_id    TEXT,
  p_items            JSONB,
  p_add_subtotal     NUMERIC,
  p_add_total        NUMERIC,
  p_notes            TEXT,
  p_performed_by     TEXT,
  p_idempotency_key  TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing_event_id TEXT;
  v_order        orders%ROWTYPE;
  v_item         JSONB;
  v_new_item_ids TEXT[] := '{}';
  v_new_subtotal NUMERIC;
  v_new_total    NUMERIC;
  v_merged_notes TEXT;
  v_item_summary TEXT;
BEGIN
  -- Idempotency fast-path: a retried request (double-click / network retry
  -- with the same client-generated key) returns the original outcome
  -- instead of inserting a second batch of items.
  IF p_idempotency_key IS NOT NULL THEN
    SELECT id INTO v_existing_event_id FROM order_events
      WHERE order_id = p_order_id AND idempotency_key = p_idempotency_key;
    IF v_existing_event_id IS NOT NULL THEN
      RETURN jsonb_build_object(
        'ok', true, 'alreadyExists', true, 'orderId', p_order_id, 'newItemIds', '[]'::jsonb
      );
    END IF;
  END IF;

  -- Lock the order row so a concurrent Order More submission for the same
  -- order (two devices, or a race between a legitimate retry and the
  -- original request) serializes instead of both reading the same stale
  -- subtotal/total and one overwriting the other's addition.
  SELECT * INTO v_order FROM orders
    WHERE id = p_order_id AND restaurant_id = p_restaurant_id
    FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'order_not_found');
  END IF;

  IF v_order.type <> 'pickup' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type', 'type', v_order.type);
  END IF;

  -- Eligible only while the order is still actively in the kitchen pipeline
  -- (already confirmed by a waiter, not yet completed/cancelled/void).
  -- Revalidated here — not just in the calling route — so a stale client
  -- (order completed/cancelled by someone else moments earlier) cannot
  -- attach new items to a finished order (§A19).
  IF v_order.status NOT IN ('pending', 'preparing', 'prepared') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_eligible', 'status', v_order.status);
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO order_items (id, order_id, menu_item_id, name, qty, price, subtotal)
    VALUES (
      v_item->>'id', p_order_id, NULLIF(v_item->>'menuItemId', ''),
      v_item->>'name', (v_item->>'qty')::INTEGER, (v_item->>'price')::NUMERIC, (v_item->>'subtotal')::NUMERIC
    );
    v_new_item_ids := array_append(v_new_item_ids, v_item->>'id');
  END LOOP;

  v_new_subtotal := round((COALESCE(v_order.subtotal, 0) + p_add_subtotal)::numeric, 2);
  v_new_total    := round((COALESCE(v_order.total, 0)    + p_add_total)::numeric, 2);

  -- Merge notes rather than overwrite (same convention as the dine-in
  -- "append to awaiting_waiter order" path in POST /api/orders).
  v_merged_notes := CASE
    WHEN p_notes IS NOT NULL AND p_notes <> '' THEN
      CASE WHEN v_order.notes IS NOT NULL AND v_order.notes <> ''
           THEN v_order.notes || ' | ' || p_notes
           ELSE p_notes END
    ELSE v_order.notes
  END;

  UPDATE orders SET
    subtotal   = v_new_subtotal,
    total      = v_new_total,
    notes      = v_merged_notes,
    updated_at = now()
  WHERE id = p_order_id;

  SELECT string_agg((i->>'qty') || ' x ' || (i->>'name'), ', ')
    INTO v_item_summary FROM jsonb_array_elements(p_items) i;

  INSERT INTO order_events (id, order_id, event_type, performed_by, note, idempotency_key)
  VALUES (
    p_event_id, p_order_id, 'OrderMoreItemsAdded', p_performed_by,
    'Order More: ' || COALESCE(v_item_summary, ''), p_idempotency_key
  );

  RETURN jsonb_build_object(
    'ok', true, 'alreadyExists', false, 'orderId', p_order_id,
    'newItemIds', to_jsonb(v_new_item_ids),
    'newSubtotal', v_new_subtotal, 'newTotal', v_new_total
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.add_pickup_order_items TO service_role;
REVOKE EXECUTE ON FUNCTION public.add_pickup_order_items FROM PUBLIC;
